In [3]:
import numpy as np

In [4]:
a=np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [5]:
a+2

array([3, 4, 5, 6])

In [6]:
a-2

array([-1,  0,  1,  2])

In [7]:
a*2

array([2, 4, 6, 8])

In [8]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [9]:
b=np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [10]:
a**2

array([ 1,  4,  9, 16])

In [11]:
#take the sin of values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
#take the cos of values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
####linear algebra

In [14]:
a=np.ones((2, 3))
print(a)
b=np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
#find the determinant
c=np.identity(3)
soln=np.linalg.det(c)
print(soln)


1.0


In [16]:
####statistics

In [17]:
stats=np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [18]:
np.min(stats, axis=1)

array([1, 4])

In [19]:
np.max(stats)

np.int64(6)