In [1]:
import numpy as np

In [3]:
before=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
after=before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#vertically stacking vectors
v1=np.array([1, 2, 3, 4])
v2=np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
#horizontally stacking vectors
h1=np.ones((2, 4))
print(h1)
h2=np.zeros((2, 2))
print(h2)
np.hstack((h1, h2))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])