In [6]:
import numpy as np

In [7]:
#all zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
#3d
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.zeros((2, 3, 3, 2))  #looking from right to left. here, 2 is the column, 3 is the row, 3 is the number of such arrays, and finally 2 is the number of blocks the arrays need to be in

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [10]:
#all 1's matrix
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
#any other matrix
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
#matrix of random decimal numbers
np.random.rand(4, 2)

array([[0.9049261 , 0.06758907],
       [0.4732967 , 0.36548759],
       [0.08039513, 0.99049055],
       [0.95502511, 0.19769122]])

In [13]:
#random integer values
np.random.randint(-3, 7, size=(3,3))   #here, -3 and 7 are the starting values(included) and ending value(excluded)

array([[ 1, -2, -3],
       [ 3,  5,  3],
       [ 1,  3,  1]])

In [14]:
np.identity(4) #one parameter is enough as by nature, identity matrix is a square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#repeat an array
a=np.array([[1, 2, 3]])
r1=np.repeat(a, 3, axis=0 )  #here, a is repeated thrice and axis = 0 means repeat along rows
                             #if axis=1, then it means repeat along columns
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
a=np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 9, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [20]:
a=np.ones((5, 5), dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
a[1:4, 1:4]=0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [23]:
a[2, 2]=9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [24]:
a=np.array([1, 2, 3])
b=a
print(b)

[1 2 3]


In [25]:
b[0]=100
print(b)

[100   2   3]


In [26]:
print(a)

[100   2   3]


In [27]:
a=np.array([1, 2, 3])
b=a.copy()
print(a)
b[0]=100
print(b)

[1 2 3]
[100   2   3]
