In [ ]:
import numpy as np

In [ ]:
a=np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
a.shape

(2, 8)

In [ ]:
#get specific element [row, column]
#to get 13 from above we do the following:
a[1, 4]

np.int64(13)

In [ ]:
#get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#get specific column
a[:, 2]

array([ 3, 11])

In [ ]:
#[startindex: endindex: step size]
a[0, 1:8:2]       #here, the 0 indicates row if it was a 1D array, we dont have to mention the row

array([2, 4, 6, 8])

In [ ]:
#changing an element in an array
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [9, 10, 11, 12, 13, 14, 15, 16]
])

a[1, 5] = 20

print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 20 15 16]]
